### ISSUE TITLE
JVM args: 'a'

### ISSUE THREAD

**Issue by zkendall** [cbeust/testng-eclipse#197] opened 2015-12-01 00:19 UTC
When I restart eclipse, the Preferences > TestNG > Run/Debug has the "JVM args" set to the letter "a".

Any ideas?

**Comment by missedone** [comment] 2015-12-01 01:17
em... not quite sure...
what if you clean that field and save, next time after restarting eclipse, will the letter "a" come back?

**Comment by zkendall** [comment] 2015-12-07 18:19
Yes, that's what I'm noticing.

**Comment by missedone** [comment] 2015-12-08 07:39
could you switch to a new workspace and have a try?

**Comment by missedone** [comment] 2015-12-08 10:27
btw, do you see any error relate to this on the error view: click "window" on top level menu -> show others -> error.
if so, pls paste the detail here, thanks

**Comment by zkendall** [comment] 2015-12-14 22:15
I made a new workspace but loaded the same project. There is no error, just an info event:

```
[TestNGLaunchConfigurationDelegate] Launching:
  Classpath: /Users/...
  VMArgs:    -ea a
  Class:     org.testng.remote.RemoteTestNG
  Args:      -serport ...
java -ea a -classpath...

eclipse.buildId=4.5.1.M20150904-0015
java.version=1.8.0_66
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -keyring /Users/zack/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -data /Users/zack/Documents/workspace/test -product org.eclipse.epp.package.java.product -keyring /Users/zack/.eclipse_keyring -showlocation
```

**Comment by missedone** [comment] 2015-12-18 00:16
well, how about delete the setting from .pref file, 
1. close your eclipse
2. use your text editor to open `${workspace_loc}/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.testng.eclipse.prefs`, for example here is mine (to simulate your case):
```
.outdir=/target/test-output
_TESTNG_ECLIPSE.useProjectJar=true
eclipse.preferences.version=1
jvmArgs=a
```
remove the full line of `jvmArgs=a` and save
3. start your eclipse to observe if the issue is gone

thanks

**Comment by zkendall** [comment] 2015-12-18 22:40
That seemed to do it. Thanks a lot!

**Comment by zkendall** [comment] 2015-12-19 01:05
Actually it re-showed up on its own.. :/

**Comment by missedone** [comment] 2015-12-22 14:36
hi,
i encountered this issue as well with latest version of plugin.
will dig into this later.

**Comment by zkendall** [comment] 2015-12-22 18:31
Yay. I'm not crazy!

**Comment by missedone** [comment] 2015-12-23 09:32
hi @zkendall 
could you have a look at file `~/.eclipse/org.eclipse.oomph.setup/setups/user.setup`, do you see something like this:

```xml
      <setupTask
          xsi:type="setup:PreferenceTask"
          key="/instance/org.testng.eclipse/jvmArgs"
          value="a"/>
```

this file is used to sync up eclipse preferences across diff eclipse instance on your machine.
testng plugin itself won't add anything like 'a' to the Run/Debug jvmArgs
in my case, i use one instance Mars.1 to simulate your issue which saved 'a' as jvmArgs, later when i start another instance like Neon M4, the preference propagate to this new instance.

after removing it, so far so good now.

**Comment by missedone** [comment] 2015-12-24 05:56
also, please check all your eclipse instance to remove the wrong jvmArgs preference.

**Comment by zkendall** [comment] 2015-12-30 00:26
Yeah I do have that. Removing now.

**Comment by missedone** [comment] 2016-02-14 02:11
close it for now, let's reopen if the issue come back.

**Closed by missedone** 2016-02-14 02:11 UTC
