### ISSUE TITLE
Eclipse: Can't recognize runtime TestNG version

### ISSUE THREAD

**Issue by dramer** [cbeust/testng-eclipse#243] opened 2016-03-29 16:00 UTC
### Expected behaviour
run the testng test within Eclipse
### Actual behaviour
Error: Eclipse: Can't recognize runtime TestNG version

### Steps to reproduce
1. try to run any test in my project.
2. 
3. 

### Running Configuration
* Plugin Version: 
* (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")

  TestNG	6.9.11.201603260617	org.testng.eclipse.feature.group	Cedric Beust

* (Optional) Operating System: 

Debugging a test in Eclipse, I received "Can't recognize runtime TestNG version"

I just upgraded testNG thru Eclipse to 6.9.11 also upgraded Java to 1.7.0_51

Now I receive the following error in Eclipse: Can't recognize runtime TestNG version

Any help would be appreciated.

**Comment by cbeust** [comment] 2016-03-29 16:22
ping @missedone

-- 
Cédric

**Comment by missedone** [comment] 2016-03-29 16:27
link https://github.com/cbeust/testng/issues/1012

**Comment by missedone** [comment] 2016-03-29 16:31
hi @dramer 
could you share a small sample project so that I can reproduce this issue?
thanks

**Comment by dramer** [comment] 2016-03-29 16:46
hi @missedone  let me try to build a new project. The project I'm using is really large.

**Comment by chen-zhuo** [comment] 2016-03-29 17:07
Same issue here. Don't think it's a project-related issue either. I am using Eclipse Luna for Java EE Developers (64 bit version) on Mac OS.

Anyway, @missedone could you provide the link of the previous version? The previous release seems to be 6.9.5 with url https://github.com/cbeust/testng-eclipse/archive/6.9.5.zip. Which url should I type in Eclipse when I install new software?

http://beust.com/eclipse-old/eclipse_6.9.5.201510061138
http://beust.com/eclipse-old/eclipse_6.9.5.201506120235 Java Editor Template
http://beust.com/eclipse-old/eclipse_6.9.5.201506081335
http://beust.com/eclipse-old/eclipse_6.9.5.201506081334
http://beust.com/eclipse-old/eclipse_6.9.5.201505260426
http://beust.com/eclipse-old/eclipse_6.9.5.201505260410
http://beust.com/eclipse-old/eclipse_6.9.5.201505260407
http://beust.com/eclipse-old/eclipse_6.9.5.201505251947

Thanks.

**Comment by dramer** [comment] 2016-03-29 17:11
Was looking at the run configuration.  should TestNG be in the class path?
![screen shot 2016-03-29 at 10 12 50 am](https://cloud.githubusercontent.com/assets/4681726/14116829/95386176-f596-11e5-9ced-0c37e62765f5.png)

**Comment by dramer** [comment] 2016-03-29 17:22
@missedone  Small new project worked well. Could this be something with Maven and TestNG?

**Comment by skirkpatrick** [comment] 2016-03-29 17:32
@cbeust Does the TestNG pom.xml version need to be updated to match the gradle version? The pom is still at 6.9.11-SNAPSHOT, and the artifact is not deployed to Maven central.

**Comment by missedone** [comment] 2016-03-29 19:45
could you check the classpath of the testng process. 
by click "Window -- show view -- Error", now on the error view, do you see any relate error there?
or, you can see the command of lauching the testng process.
it could be really lengthy, you can copy it to your text editor.
then do you see any testng jar on the classpath?

**Comment by missedone** [comment] 2016-03-29 20:46
to explain more, since testng eclipse plugin 6.9.10, it need to know the runtime testng version by scan the classpat and parse the manifest.mf of the testng jar file.
and since testng eclipse plugin 6.9.11, it doesnt append the plugin embedded testng jar to the runtine process, that means, now it respects the project classpath

**Comment by missedone** [comment] 2016-03-30 08:44
@chen-zhuo 
the update-site was reverted to 6.9.10, you can uninstall and re-install the version of 6.9.10.

BTW, given a sample project can help diagnose this issue a lot.

**Comment by dramer** [comment] 2016-03-30 14:02
@missedone  trying to build a new project to check things out. I now get this error:  
The type com.google.common.base.Function cannot be resolved. It is indirectly referenced from required .class files	YYY.java	/XXX/src/com/common/XXX	line 1	Java Problem

I've never seen this error. I did copy files from my other project.

**Comment by missedone** [comment] 2016-03-30 23:31
hi @dramer 
could you assist me to diagnose this issue?
i just added some logging statement in the new plugin, hope it can lead me to the truth.

you can install it via the beta update-site:  http://testng.org/eclipse-beta
see installation instruction [here](https://github.com/cbeust/testng-eclipse)

you can use it run your original large project to reproduce the issue, then go to the "Error Log" view (click "Window -> Show View -> Error Log") to see and log entry there, especially, i'd like to see the full classpath.

thanks

**Comment by missedone** [comment] 2016-03-31 02:10
if anybody can assist the diagnose the issue is much appreciated.

**Comment by dramer** [comment] 2016-03-31 12:00
@missedone   I will work on this today!

**Comment by dramer** [comment] 2016-03-31 12:33
![screen shot 2016-03-31 at 5 29 18 am](https://cloud.githubusercontent.com/assets/4681726/14175769/213b1a8a-f702-11e5-952a-de6fa3f01cfb.png)

**Comment by dramer** [comment] 2016-03-31 12:34
@missedone   Here is the image


![screen shot 2016-03-31 at 5 29 18 am](https://cloud.githubusercontent.com/assets/4681726/14175790/3839d46a-f702-11e5-816a-cffdb9ea362a.png)

**Comment by missedone** [comment] 2016-03-31 13:14
hi @dramer 
could you run with your larger project with the newly install beta testng eclipse plugin (the plugin is globally under Eclipse)

once you got the 'Can't recognize runtime TestNG version' error, could you go to the "Error Log" view, and there could be two or three relate log entries on the view, i'd like to know the log details, especially, i want to know if testng jar is on the classpath. 
thanks

**Comment by chen-zhuo** [comment] 2016-03-31 13:31
@missedone thanks for the reply!

FYI I was trying to set up the project `https://github.com/TEAMMATES/teammates.git`. It is a bit tedious to set up though but you can try to reproduce the error. :)

**Comment by dramer** [comment] 2016-03-31 13:35
@missedone  Ok I see no errors message in the problems console.  I downloaded the bete, I see version  6.9.12.201603301608  testng.jar

Steps:
downloaded and installed the beta 6.9.12.201603301608  testng.jar
Cleaned the project
ran the testNG test, and same error showed.


Isolation:
my project says it's Maven, but I don't see a pom file ?

my new project was just a java project and all was working well yesterday. Closed Eclipse and today the new project thinks it's Maven?

**Comment by missedone** [comment] 2016-03-31 13:38
thanks @chen-zhuo 
at the time git clone the code teammates code, i got a quick the the [.classpath](https://github.com/TEAMMATES/teammates/blob/master/.classpath) where has no any testng classpathentry, so i think that's why you got the error "Can't recognize runtime TestNG version".

but i'm wondering, if there is no testng classpathentry, how could the project be built successfully (without any compile error)?

**Comment by missedone** [comment] 2016-03-31 13:43
hi @dramer 
the error should be on "Error Log" view (click "Window -> Show View -> Error Log").

regards to the Maven staff, what do you see if run the following command: `cat .project | grep maven2Nature`
if it's a maven project, you will see output like this:
```
		<nature>org.eclipse.m2e.core.maven2Nature</nature>
```

thanks

**Comment by dramer** [comment] 2016-03-31 13:51
Hi, @missedone   image of the error log.  not sure where the project thinks the pom file is!!!!!  but the warnings come after I clean the project.  The errors are when I try to run the test.

![screen shot 2016-03-31 at 6 52 33 am](https://cloud.githubusercontent.com/assets/4681726/14177829/ed76ed72-f70c-11e5-9a28-434ebe556370.png)

**Comment by missedone** [comment] 2016-03-31 13:54
hi @chen-zhuo 
the teammates git really large, i'm still cloning.

at the meanwhile, could you try add TestNG to your project classpath:
1. right click on your project  -> Build Path -> Add Library...
2. Select "TestNG" and click "Finish" button
3. now your project will looks something like this: 
<img width="338" alt="testng_prj" src="https://cloud.githubusercontent.com/assets/555134/14177917/50dda1ee-f70d-11e5-8fed-af9a9eea98b8.png">

please let know if this works for you, thanks

**Comment by missedone** [comment] 2016-03-31 13:56
hi @dramer 
i'd like to see the details of the 2nd entry on your screenshot, it's 'Can't recognize runtime TestNG version from classpath:'
could you double click the log entry, and you will see the detail, copy it and paste on your text editor, do you see testng jar on the classpath list?

(please ignore the maven warning for now)

**Comment by dramer** [comment] 2016-03-31 13:57
![screen shot 2016-03-31 at 6 59 29 am](https://cloud.githubusercontent.com/assets/4681726/14178041/c9f191da-f70d-11e5-9664-1162140b6c24.png)

**Comment by missedone** [comment] 2016-03-31 14:01
@dramer ,
oh, looks like there is no classpath for you project, how could this be?

since sounds like your project is also a regular eclipse plugin, could you follow my comments https://github.com/cbeust/testng-eclipse/issues/243#issuecomment-203951212 to add the TestNG library to your classpath?

and let me know if it works for you or not?

Again, i'd like to say, since TestNG Eclipse Plugin 6.9.11, it use whatever on your project classpath, if there is no testng jar, then the test process can't be started.

Still, i'm wondering, do you see any compile error on your test classes? since no testng jar on the classpath.

**Comment by dramer** [comment] 2016-03-31 14:10
Hi,  @missedone   the comment link, takes me to this page? can you be a little more specific on what you want me to do. I'm on a MAC!

**Comment by missedone** [comment] 2016-03-31 14:11
@dramer 
here you go:
1. right click on your project -> Build Path -> Add Library...
2. Select "TestNG" and click "Finish" button
3. now your project will looks something like this: 
<img width="338" alt="testng_prj" src="https://cloud.githubusercontent.com/assets/555134/14177917/50dda1ee-f70d-11e5-8fed-af9a9eea98b8.png">

then, run your test again.

**Comment by dramer** [comment] 2016-03-31 14:13
@missedone  For sure I have that..... Everything compiles with no errors or warnings. Are you sure this does not have something to do with my project thinking its Mavenized? How do I un-mavenize my project?


![screen shot 2016-03-31 at 7 15 27 am](https://cloud.githubusercontent.com/assets/4681726/14178583/1d794a76-f710-11e5-919c-2d74ee8ad8f7.png)

**Comment by missedone** [comment] 2016-03-31 14:19
thanks @dramer 
for now, i still don't think it's anything relate to maven.
could you show me your test launch configuration:
1. click "Run" on the top level menu -> Run Configurations
2. select your test launch configuration
3. navigate to the "Classpath" tab, something like this:
<img width="781" alt="user_entries" src="https://cloud.githubusercontent.com/assets/555134/14178703/a63cb30c-f710-11e5-8136-800fa77ec482.png">

**Comment by dramer** [comment] 2016-03-31 14:35
Hi, @missedone  well all my tests are gone..... I added the test package to source path... then I removed them..... In my project the package com.common.test is gone..... anyway to get that back?  So I created a new testNG test in the project and all worked well.. I'm just missing 1000 tests now?

![screen shot 2016-03-31 at 7 31 32 am](https://cloud.githubusercontent.com/assets/4681726/14179195/066c24cc-f713-11e5-976b-4a043ff01121.png)

**Comment by dramer** [comment] 2016-03-31 14:36
@missedone  here is my Run Configuration

![screen shot 2016-03-31 at 7 38 14 am](https://cloud.githubusercontent.com/assets/4681726/14179234/3a45912a-f713-11e5-82ea-0e3b295cae41.png)

**Comment by chen-zhuo** [comment] 2016-03-31 14:40
@missedone could you provide the link to version 6.9.11 again? The link we use to "install new software" in eclipse.

**Comment by missedone** [comment] 2016-03-31 14:46
hi @chen-zhuo 
could you install from this beta update-site http://testng.org/eclipse-beta 
thanks

**Comment by missedone** [comment] 2016-03-31 14:48
@dramer 
sorry, did you mean you missing 1000 test launch configurations?
or, do you mean you want to add your test source code to the eclipse "Source" entries so that they will get compiled and run/debug?

**Comment by dramer** [comment] 2016-03-31 14:50
@missedone  Nick I deleted the test package after removing them from the build source. Don't worry about that.  The bad news is I don't have any old tests to try and help you debug.... When I created a new  test in the old project it ran just fine.

**Comment by missedone** [comment] 2016-03-31 14:56
hi @dramer 
that's OK, thanks for you assistance, and your precious time.

so for now, I think there might be something wrong in your old Run configuration, or something i missed, i think i will add more words for the error message "*Can't recognize runtime TestNG version, could you have a check TestNG is on your project classpath and this Run/Debug launch configuration classpath*"

**Comment by dramer** [comment] 2016-03-31 14:59
@missedone  I reconstructed an old test and I get the same error.....  Here is my run configuration


![screen shot 2016-03-31 at 8 01 18 am](https://cloud.githubusercontent.com/assets/4681726/14180113/84c0cde8-f716-11e5-9f14-20c1ecde603d.png)

**Comment by dramer** [comment] 2016-03-31 15:00
@missedone  can you help me with my other project?  Why all of a sudden can't I run the test as a java, it simple give me the Maven selection under run as?

**Comment by missedone** [comment] 2016-03-31 15:01
thanks @dramer 

could you show me your test launch configuration:
1. click "Run" on the top level menu -> Run Configurations
2. select your test launch configuration
3. navigate to the "Classpath" tab, something like this:
<img width="781" alt="user_entries" src="https://cloud.githubusercontent.com/assets/555134/14178703/a63cb30c-f710-11e5-8136-800fa77ec482.png">

**Comment by missedone** [comment] 2016-03-31 15:06
hi @dramer 
let's trouble shooting in the [gitter room](https://gitter.im/cbeust/testng-eclipse)

**Comment by chen-zhuo** [comment] 2016-03-31 15:13
@missedone using TestNG version 6.9.12.201603301608, and added the build path, there is no more "Can't recognize runtime TestNG version" error dialog, but the following exception is thrown:

`java.lang.AbstractMethodError: org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(Lorg/testng/ISuite;Lorg/testng/xml/XmlTest;Ljava/util/List;)Lorg/testng/TestRunner;
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:561)
	at org.testng.SuiteRunner.init(SuiteRunner.java:157)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:46)`

and TestNG terminates immediately.

**Comment by missedone** [comment] 2016-03-31 15:18
thanks @chen-zhuo 
could you go the the "Error Log" view, and locate to the log entry of " [TestNGLaunchConfigurationDelegate]", i'd like to know the args, something like this:
```
  Args:      -serport 49319 -protocol json -version 6.9.11 -d /Users/nick/workspace/myproject/testNG-plugin-test/test ws/target/test-output /var/folders/54/wsbhhvxs4v92kc0d9rh6h2zr0000gp/T/testng-eclipse--729851143/testng-customsuite.xml
java -ea -Dfoo=bar -Dtestng.eclipse.verbose -classpath /Users/nick/workspace/myproject/testng-eclipse/testng-eclipse-plugin/lib/testng-remote.jar:/Users/nick/workspace/myproject/testNG-plugin-test/test ws/bin:/Users/nick/workspace/myproject/testng-eclipse/testng-eclipse-plugin/lib/testng.jar:/Users/nick/workspace/myproject/testng-eclipse/testng-eclipse-plugin/lib/jcommander.jar:/Users/nick/workspace/myproject/testng-eclipse/testng-eclipse-plugin/lib/bsh-2.0b4.jar:/Users/nick/workspace/myproject/testng-eclipse/testng-eclipse-plugin/lib/snakeyaml.jar org.testng.remote.RemoteTestNG -serport 49319 -protocol json -version 6.9.11 -d /Users/nick/workspace/myproject/testNG-plugin-test/test ws/target/test-output /var/folders/54/wsbhhvxs4v92kc0d9rh6h2zr0000gp/T/testng-eclipse--729851143/testng-customsuite.xml
```

thanks

**Comment by chen-zhuo** [comment] 2016-03-31 15:26
@missedone 
Args:      -serport 52684 -protocol json -version 6.9.11 -d /Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/test-output /Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/testng.xml
java -ea -Duser.timezone=UTC-Xss2m -classpath /Applications/Eclipse Luna (Java EE)/plugins/org.testng.eclipse_6.9.12.201603301608/lib/testng-remote.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/javamail/mail.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/appengine-local-runtime-shared.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/el-api.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/jsp/repackaged-appengine-ant-1.7.1.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/jsp/repackaged-appengine-ant-launcher-1.7.1.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/jsp/repackaged-appengine-jasper-6.0.29.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/jsp/repackaged-appengine-jasper-el-6.0.29.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/jsp/repackaged-appengine-tomcat-juli-6.0.29.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/jsp-api.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/shared/servlet-api.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/appengine-tools-api.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/appengine-api-labs/v1/appengine-api-labs.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/appengine-endpoints/v1/appengine-endpoints-deps.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/appengine-endpoints/v1/appengine-endpoints.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/jsr107/v1/appengine-jsr107cache-1.9.27.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/jsr107/v1/jsr107cache-1.1.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/user/appengine-api-1.0-sdk-1.9.27.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/datanucleus/v1/datanucleus-appengine-1.0.10.final.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/datanucleus/v1/datanucleus-core-1.1.5.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/datanucleus/v1/datanucleus-jpa-1.1.5.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/datanucleus/v1/geronimo-jpa_3.0_spec-1.1.1.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/datanucleus/v1/geronimo-jta_1.1_spec-1.1.1.jar:/Users/David_CHEN_ZHUO/Documents/Google App Engine SDK 1.9.27/lib/opt/user/datanucleus/v1/jdo2-api-2.3-eb.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/target/test-classes:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/classes:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/gson-2.2.2.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/xercesImpl-2.9.1.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/appengine/appengine-remote-api.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/appengine/appengine-testing.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/appengine/appengine-api.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/appengine/appengine-api-stubs.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/appengine/appengine-api-labs.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/selenium/selenium-server-standalone-2.46.0.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/resources/lib/httpunit/httpunit.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/appengine-gcs-client-0.3.13.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/guava-15.0.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/google-api-services-storage-v1beta2-rev47-1.18.0-rc.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/jackson-core-2.1.3.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/gcs dependencies:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/google-api-client-appengine-1.18.0-rc.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/google-api-client-1.18.0-rc.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/repackaged-appengine-jakarta-jstl-1.1.2.jar:/Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/main/webapp/WEB-INF/lib/repackaged-appengine-jakarta-standard-1.1.2.jar:/Applications/Eclipse Luna (Java EE)/plugins/org.testng.eclipse_6.9.12.201603301608/lib/testng.jar:/Applications/Eclipse Luna (Java EE)/plugins/org.testng.eclipse_6.9.12.201603301608/lib/jcommander.jar:/Applications/Eclipse Luna (Java EE)/plugins/org.testng.eclipse_6.9.12.201603301608/lib/bsh-2.0b4.jar:/Applications/Eclipse Luna (Java EE)/plugins/org.testng.eclipse_6.9.12.201603301608/lib/snakeyaml.jar org.testng.remote.RemoteTestNG -serport 52684 -protocol json -version 6.9.11 -d /Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/test-output /Users/David_CHEN_ZHUO/Documents/Eclipse Luna (Java EE) Workspace/teammates/src/test/testng.xml

**Comment by chen-zhuo** [comment] 2016-03-31 15:27
@missedone 
[Message.txt](https://github.com/cbeust/testng-eclipse/files/197956/Message.txt)

**Comment by dramer** [comment] 2016-03-31 20:41
@missedone  when I create a new java file with an inner class called test, Eclipse is not creating a Run configuration for the $Test  what would cause that?

**Comment by missedone** [comment] 2016-04-01 12:40
thanks @chen-zhuo
the teammates project is very helpful, the root cause is selenium-server-standalone-2.46.0.jar packages the testng classes (version of 6.8.5):
<img width="317" alt="testng_in_selenium" src="https://cloud.githubusercontent.com/assets/555134/14207011/1fd88914-f7cc-11e5-8f82-5d9a6dbbe486.png">

the testng eclipse plugin sucks at parsing the TestNG version in this case.

**Comment by missedone** [comment] 2016-04-01 16:13
hi @chen-zhuo 
could you try with the latest beta plugin http://testng.org/eclipse-beta
and let me know if it works.

thanks

**NOTE**, before you run the test, please remove "TestNG" library out of the project build path since "teammates" depends on `selenium-server-standalone-2.46.0.jar` which already has testng classed assembled in the fat jar.
<img width="540" alt="remove_build_path" src="https://cloud.githubusercontent.com/assets/555134/14212895/e5cf3f06-f7e9-11e5-99c3-f7ea4aa9f67b.png">

**Comment by chen-zhuo** [comment] 2016-04-02 11:52
@missedone I tried with the latest beta version and it seems working fine! :)

**Comment by missedone** [comment] 2016-04-02 12:27
thanks @chen-zhuo 
very glad to know :smiley:

**Comment by missedone** [comment] 2016-04-02 15:49
closed this issue.

please feel free to re-open it if you still encounter issue.
thanks

**Closed by missedone** 2016-04-02 15:49 UTC
