### ISSUE TITLE
Unable to launch TestNG Test - ClassCastException: org.eclipse.jdt.core.dom.MarkerAnnotation cannot be cast to org.eclipse.jdt.core.dom.SingleMemberAnnotation

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#294] opened 2016-10-25 07:58 UTC
> I'm trying to launch some TestNG tests in Eclipse, which were working earlier. But now it doesn't run at all, and shows a dialog saying 
"Launching myclassname has encountered a problem." 
It doesn't happen to all the tests in the package, but only to some of them. 
What could be the reason? Any help to narrow down the problem would be really appreciated.

An internal error occurred during: "Launching myclassname". java.lang.ClassCastException: 

org.eclipse.jdt.core.dom.MarkerAnnotation cannot be cast to org.eclipse.jdt.core.dom.SingleMemberAnnotation at org.testng.eclipse.util.param.TestNGMethodParameterVisitor.getParametersMap(TestNGMethodParameterVisitor.java:182) at org.testng.eclipse.util.param.ParameterSolver.parseParameterNames(ParameterSolver.java:130) at org.testng.eclipse.util.param.ParameterSolver.solveParameters(ParameterSolver.java:113) at org.testng.eclipse.util.param.ParameterSolver.getParameterNames(ParameterSolver.java:91) at org.testng.eclipse.util.param.ParameterSolver.solveParameters(ParameterSolver.java:60) at org.testng.eclipse.ui.util.ConfigurationHelper.getLaunchSuites(ConfigurationHelper.java:416) at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.createVMRunner(TestNGLaunchConfigurationDelegate.java:296) at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launchTypes(TestNGLaunchConfigurationDelegate.java:161) at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launch(TestNGLaunchConfigurationDelegate.java:91) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739) at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039) at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

From http://stackoverflow.com/q/40233637/4234729

**Comment by kanayikkaran** [comment] 2016-10-26 05:38
I've upgraded TestNG Eclipse plug-in to version 6.9.13.201609291640, and I guess that is when the issue started.

**Comment by missedone** [comment] 2016-10-26 07:31
right, this issue caused by PR #275 , will try to fix it soon

**Comment by missedone** [comment] 2016-10-26 07:57
fixed in PR #295

**Comment by kanayikkaran** [comment] 2016-10-26 08:03
Excellent. Could you please let me know when we'll be able to download it to Eclipse?

**Comment by missedone** [comment] 2016-10-26 08:12
it's available in the beta update site now: http://testng.org/eclipse-beta

**Comment by kanayikkaran** [comment] 2016-10-26 09:59
Updated to beta. I could run the tests again! Thank you so much!

**Comment by missedone** [comment] 2016-10-26 10:27
Good to know, thank you for reporting the issue.

**Closed by missedone** 2016-10-26 10:27 UTC

**Comment by Anand093** [comment] 2018-05-07 12:44
If we pass constants from some interface in parameter, that error 
Unable to launch TestNG Test - ClassCastException: org.eclipse.jdt.core.dom.MarkerAnnotation cannot be cast to org.eclipse.jdt.core.dom.SingleMemberAnnotation

still appears
@Parameters({EXECUTION_ENV})
@Test(priority =1, description = "ABCD")

Here EXECUTION_ENV is a variable & it holds some value, if we directly paste value, it works fine, but if we use some variable, then it shows error.
Plz look in to this issue

**Comment by youming-lin** [comment] 2023-08-02 15:43
Just encountered similar issue as @ Anand093 
See my new issue with code example and error message.
