### ISSUE TITLE
Stop-button is not working in Eclipse 3.6 (Helios)

### ISSUE THREAD

**Issue by Lostprophet85** [cbeust/testng-eclipse#60] opened 2012-06-20 09:57 UTC
First off, I have Eclipse Helios Service Release 2 and version 6.5.2.20120616_1545 of the TestNG-Eclipse Plugin (which is the latest version according to my Eclipse) installed.
When I run a few Test-classes in Eclipse Helios and try to stop the current run via the stop-button, nothing happens, the run finishes regularly. I switched output to verbose-mode to check and no stop-signal whatsoever was being issued, it looks like the button has no function at the moment.

**Comment by missedone** [comment] 2015-10-12 15:18
let's reopen it if anyone else encounter the same issue.

**Comment by missedone** [comment] 2015-10-19 15:36
re-open since I can reproduce this
fixed in PR #179

**Closed** 2015-10-19 23:30 UTC
