### ISSUE TITLE
Unable to install testNG

### ISSUE THREAD

**Issue by pragya261990** [cbeust/testng-eclipse#258] opened 2016-06-13 07:05 UTC
### Expected behaviour

It should be easily downloaded as given in steps.
Enter the update site URL in "Work with:" field in eclipse:

    Update site for release: http://beust.com/eclipse

### Actual behaviour

It shows this error
Unable to read repository at http://beust.com/eclipse./content.xml.
Unable to read repository at http://beust.com/eclipse./content.xml.
Unrecognized Windows Sockets error: 10107: create

### Steps to reproduce
1. Open eclipse 
2. Help > Install new software
3. Enter the update site URL in "Work with:"  http://beust.com/eclipse
4. Click on ok

### Running Configuration
* Plugin Version: 
* (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")
* (Optional) Operating System:  Windows 8

**Comment by missedone** [comment] 2016-06-14 01:44
hi @pragya261990
do you still encounter with the issue now?
since i just tried with the release update site, things work fine.

**Comment by subroto08820** [comment] 2016-06-29 16:21
Hello, 

I was able to follow all the steps and at the last step is to accept the license agreement and click next to install. However, the Next button is not getting enabled even after I accept the license agreement. So the software is not installed. Please help.

Thanks 

Subrata

**Comment by subroto08820** [comment] 2016-06-29 16:22
Sorry forgot to mention, my OS is Windows 10. Thx

**Comment by missedone** [comment] 2016-07-03 14:27
hi @subroto08820 
to be honest, the "Next" button of installation dialog is not controlled by testng plugin.
could you try install again? I suspect there could be some network issue behind.

**Comment by missedone** [comment] 2016-07-10 07:52
closing this since it's not a bug.

just FYI. testng eclipse plugin 6.9.12 was released, you may have a try again.

**Comment by subroto08820** [comment] 2016-07-11 20:39
Hello Nick,

Need help here. Enclosing screen shots I took during installation of
TestNG. As you will see I can't install as the "Next" button is disabled
even after accepting the license agreement. May be you could suggest to me
where else can I install TestNG. Appreciate your help.

Thanks

Subrata

Subrata Mukherjee

**Comment by missedone** [comment] 2016-07-12 00:11
hi @subroto08820 
do you see any error on the "Error Log": click the "Window" on top menu -> show view -> Error Log.

or, could  you try install testng plugin on a pure clean eclipse instance?

**Comment by subroto08820** [comment] 2016-07-12 01:15
enclosing error message captured..Thanks.

Subrata Mukherjee

**Comment by missedone** [comment] 2016-07-12 02:36
hi @subroto08820 
could you attach the error message on github rather than email?
thanks

**Comment by hubertgrzeskowiak** [comment] 2016-08-09 16:34
Probably you just need to press "Finish" instead of "Next"...

**Comment by subroto08820** [comment] 2016-08-09 19:07
Hello all, You can close this one. I installed a new Eclipse and then
TestNG successfully.
Thanks all,

Subrata

Subrata Mukherjee

**Closed** 2016-08-09 19:12 UTC

**Comment by juherr** [comment] 2017-07-14 08:49
@missedone Someone has the same issue: https://stackoverflow.com/q/44926468/4234729

**Comment by missedone** [comment] 2017-07-14 09:36
yep, I know it's frustrated, but I don't have much idea about the root cause, so created a troubleshooting pag, hoping it can help people workaround the installation issue: https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md
