### ISSUE TITLE
Running the tests using the TestNG plugin, produces this error: "Could not find or load main class"

### ISSUE THREAD

**Issue by amascheroni** [cbeust/testng-eclipse#290] opened 2016-10-15 16:25 UTC
### Expected behaviour

When you right click on a Test, select Run As -> TestNG Test, it should run the test
### Actual behaviour

When you right click on a Test, select Run As -> TestNG Test, it produces this error: "Could not find or load main class"
However, I have downgraded the plug-in version to 6.9.12.201607091356 and it is working well again. So I think this issue is only happening with the latest one.
### Steps to reproduce
1.  Right click on a Test
2. Select Run As
3. Select TestNG Test
### Running Configuration
- Plugin Version: Last version - 6.9.13.201609291640
- (Optional) Operating System: Windows 7, Windows 8.1 and Windows 10

**Comment by missedone** [comment] 2016-10-16 01:10
hi @amascheroni 
could you share a sample project to reproduce this issue?

here is my experience, that I encountered similar issue sometime, I rebuild my java project before run the test, then things work.

**Comment by amascheroni** [comment] 2016-10-16 03:36
Hi @missedone , thanks for your quick reply!

Yes, I tried that also but I was not able to make it happen. I don't have any public project to share, but I think I can create a similar one with the same characteristics. 

I will try to share it by tomorrow's EOD

**Comment by missedone** [comment] 2016-12-09 16:03
@amascheroni , do you still see this issue in latest release 6.10.0.201612030230 ?

**Comment by maulikcool** [comment] 2017-07-25 07:39
Is that issue resolved? I am facing the same issue.

**Comment by missedone** [comment] 2017-07-25 08:57
hi @maulikcool , this is still open since need more info to figure the issue.
could you share the launch arguments? you can get it: "navigate top level menu -> Windows -> Show View -> Error Log", then double click the detail of entry "[TestNGLaunchConfigurationDelegate] Launching"

**Comment by maulikcool** [comment] 2017-07-25 09:15
![capture](https://user-images.githubusercontent.com/6253837/28564821-dcfd1ee2-7147-11e7-9d3b-de496631251a.PNG)
Kindly find the screenshot.

**Comment by maulikcool** [comment] 2017-07-25 09:16
![capture](https://user-images.githubusercontent.com/6253837/28564886-15bef37c-7148-11e7-8bbc-5eb0fa691e92.PNG)

**Comment by missedone** [comment] 2017-07-25 09:38
could your expand the Message text of "[TestNGLaunchConfigurationDelegate] Launching", there will be more detail.

**Comment by missedone** [comment] 2017-07-25 09:46
for the screenshot in comment https://github.com/cbeust/testng-eclipse/issues/290#issuecomment-317678991 "Stop the socket server ...", did you manually cancel the testng process? i'd like to figure out where it came from, and whether I need to concern it. thx

**Comment by amascheroni** [comment] 2017-08-15 19:13
I think I found the cause of the issue, it's a bug related to reportng

In the pom.xml, when you have spaces in the <org.uncommons.reportng.title> field, for example "TEST SUITE", then.. at opening the error log and clicking in the  [TestNGLaunchConfigurationDelegate] launching detailes, I was seeing something like this:

 VMArgs:    -ea -Dorg.uncommons.reportng.escape-output=false -Dorg.uncommons.reportng.title=TEST SUITE
  Class:     org.testng.remote.RemoteTestNG

And then the log said "Could not find or load main class SUITE"

After removing that space in that field, I was able to run the test successfully. 

I did more testing on this, and definitely, that was the cause of that error.

**Comment by missedone** [comment] 2017-08-15 23:06
Thx for the analysis, let me see what I can do in testng eclipse plugin.

**Comment by missedone** [comment] 2017-08-15 23:20
@amascheroni , now it looks like the same issue as #336, which is fixed in latest beta: `http://beust.com/eclipse-beta`, could you verify it?

**Comment by amascheroni** [comment] 2017-08-16 14:03
@missedone , latest beta definitely works as expected! :)

That solves the issue.

Thank you!

**Comment by missedone** [comment] 2017-08-16 16:26
thanks for the confirmation, closing it now.

**Closed by missedone** 2017-08-16 16:26 UTC
Labels: p: need more info

**Comment by prakash3112** [comment] 2020-01-15 08:11
![image](https://user-images.githubusercontent.com/23214821/72416435-aa4fbe00-379c-11ea-9cdc-2adc711d5979.png)

**Comment by prakash3112** [comment] 2020-01-15 08:11
Error: Could not find or load main class org.testng.TestNG

**Comment by missedone** [comment] 2020-01-15 08:21
@prakash3112 not sure how you setup your automation test, is testng on the classpath?
